### ISSUE TITLE
RandomFu is a huge dependency

### ISSUE THREAD

**Issue by isovector** [isovector/polysemy-zoo#16]
Dang its _real_ big. Compilation times shot up drastically upon including it. I think we should think about moving it out to a separate package (`polysemy-random-fu` maybe?).

![wreq](https://user-images.githubusercontent.com/307223/58756767-f7607780-84cc-11e9-962e-2c9ec024524e.png)

**Comment by isovector** [comment]
Before: ![wreq2](https://user-images.githubusercontent.com/307223/58770583-cbe99580-857d-11e9-9b92-279efe43329b.png)

**Comment by adamConnerSax** [comment]
Separate package is fine! Or you can just drop it. I still have it in knit-haskell (hadn’t upgraded yet!) so I’m personally indifferent at the moment.

**Comment by isovector** [comment]
@adamConnerSax would you want to be the maintainer of such a package? I'd prefer it be you instead of me, since I don't know anything about randomfu!

**Comment by adamConnerSax** [comment]
Sure! You care if it’s on stackage? I’ve never dealt with that.

**Comment by isovector** [comment]
I don't care! But putting it on stackage turns out to be super easy:
https://github.com/commercialhaskell/stackage/pull/4562/files

**Comment by adamConnerSax** [comment]
I’ve seen that! Does it only work if you use hpack or stack? I’m sort of all cabal but willing to learn hpack...
You want me to just make a package with just RandomFu and publish or will you do it, leave in this repo and make me the maintainer?

**Comment by adamConnerSax** [comment]
Bump.  Just making sure you're not waiting on me for something...
I'm happy to take over whatever when you want me to or to leave things as they are or whatever.

**Comment by isovector** [comment]
Thanks for the reminder --- totally forgot about this. I'd prefer if you are solely responsible for the package:

1. Moving it into its own repo
2. Publishing it on hackage

if you're cool with that. Afterwards I'd be happy to link to your package from this one!

**Comment by adamConnerSax** [comment]
Sure.  Might not happen until next week.  
Same namespacing, that is, call the module "Polysemy.RandomFu"?  Or do you want something different when they are external?
Maybe you should add an "EffectsPackages.md" file here with links?  Or a section at the bottom of the readme?

**Comment by isovector** [comment]
The module name is fine! The dream is that no effects are more privileged
than any others. Good idea about the markdown file; will do after the
package is published.

**Comment by isovector** [comment]
So my plan is to push a new version of polysemy-zoo that exludes `Polysemy.RandomFu`. Then the module name is available to you, you can link against `polysemy-zoo` for `Polysemy.MTL`, and put #20 in your package.

**Comment by adamConnerSax** [comment]
That works!
Also, I've noticed that this (https://github.com/kowainik/co-log/tree/master/co-log-polysemy) exists.  I don't know if it has any tests nor have I tried to use it, but it's there, in case you're interested in adding it to the list.

**Comment by isovector** [comment]
`polysemy-zoo-0.2.0.0` is up, without the `RandomFu` stuff, so the ball is now in your court, @adamConnerSax. Thanks again for your work on this!

**Comment by adamConnerSax** [comment]
Had a few minutes today and it was easier than I thought to re-arrange.

https://hackage.haskell.org/package/polysemy-RandomFu-0.1.0.0

**Comment by isovector** [comment]
Awesome. I'll add it to the PR.

PS, if you find that hacakge refuses to build your haddocks (it's an issue with the plugin, I think), get back in touch and I can walk you through it.

**Comment by adamConnerSax** [comment]
I could use that walkthrough!  Also effects my knit-haskell package.

**Comment by isovector** [comment]
I use @ChrisPenner's `haddock-up` script: https://github.com/ChrisPenner/dotfiles/blob/master/bin/haddock-up -- this lets you upload haddocks, instead of relying on hackage.

But haddock is broken when using plugins: https://github.com/haskell/haddock/issues/900. So the solution is to comment out the `-fplugin` bits, and to use `-fdefer-type-errors`. I just switch which parts of this are commented out before running haddock-up:

https://github.com/isovector/polysemy-zoo/blob/488c961945b9bbd64806199e5fe991f57f7e83ac/package.yaml#L32-L37

**Comment by adamConnerSax** [comment]
Cool!  I'll give it a try!

**Comment by Avi-D-coder** [comment]
@isovector I thought I read somewhere this is fixed in ghc-8.8. Is that true?

**Comment by isovector** [comment]
@Avi-D-coder I think so

**Comment by ocharles** [comment]
I mentioned before that uploading docs should just be: `cabal upload -d --publish`. No need for external tools. I'd be curious if that doesn't work.

**Comment by isovector** [comment]
@ocharles i don't have cabal! i don't know how to cabal!

**Comment by ocharles** [comment]
absolute mad lad

**Comment by adamConnerSax** [comment]
That worked!  For clarity, since there was some v1,v2 cabal dancing:
1. cabal v2-haddock --haddock-for-hackage
2. cabal upload -d --publish /Path/to/haskell/libs/knit-haskell/dist-newstyle/knit-haskell-0.5.0.0-docs.tar.gz

**Comment by ocharles** [comment]
Strange, mine doesn't even require two steps. Is this the latest stable Cabal?

**Comment by adamConnerSax** [comment]
It’s at least 2.4.
When I try to just do “publish” it runs into a dependency issue because it seems to be a v1 command? So I build the haddock using the v2 command and then upload. But maybe there’s a better way?

**Comment by ocharles** [comment]
Yes, `cabal upload --publish -d`, as I keep saying :stuck_out_tongue: If you show me what that produces, I might be able to see what's going on. I'm sure I did exactly this only a day or so ago with no problems on one of my repos.

**Comment by adamConnerSax** [comment]
Didn't realize you wanted the details.  Here you go!

After ```cabal --version```
```
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library 
```

After ```cabal upload --publish -d```

```
No documentation tarball specified. Building a documentation tarball with
default settings...
If you need to customise Haddock options, run 'haddock --for-hackage' first to
generate a documentation tarball.
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
[__0] trying: polysemy-RandomFu-0.1.0.0 (user goal)
[__1] unknown package: random-source (dependency of polysemy-RandomFu)
[__1] fail (backjumping, conflict set: polysemy-RandomFu, random-source)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: polysemy-RandomFu, random-source
Trying configure anyway.
Configuring polysemy-RandomFu-0.1.0.0...
Warning: The flag --disable-executable-profiling is deprecated. Please use
--disable-profiling instead.
cabal: Encountered missing dependencies:
polysemy >=0.3,
polysemy-plugin >0.2.0.0 && <0.4.0.0,
polysemy-zoo >=0.2,
random-fu >=0.2.5.0 && <0.3.0.0,
random-source >=0.3 && <0.4.0.0
```

**Comment by ocharles** [comment]
Strange, it almost looks like you need to `cabal update`, so cabal knows about `random-source`
